[build]
     command = "cd matchmystack-fd/client && npm install && npm run build:client"
     publish = "matchmystack-fd/client/dist"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200